# Generated by Django 3.1.2 on 2021-01-12 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, default=None, max_length=50)),
                ('LastName', models.CharField(blank=True, default=None, max_length=50)),
                ('Email', models.CharField(blank=True, default=None, max_length=50)),
                ('Message', models.CharField(blank=True, default=None, max_length=50)),
                ('DateMessage', models.DateField(auto_now=True)),
            ],
        ),
    ]
