# Generated by Django 3.1.2 on 2021-01-14 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Rut', models.CharField(default=None, max_length=50)),
                ('Name', models.CharField(default=None, max_length=50)),
                ('LastName', models.CharField(default=None, max_length=50)),
                ('Address', models.CharField(default=None, max_length=50)),
                ('Email', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
