# Generated by Django 3.1.2 on 2021-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='test',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
