# Generated by Django 3.1.2 on 2021-02-10 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(default=None, max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.CharField(default=None, max_length=50, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='LastName',
            field=models.CharField(default=None, max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Nationality',
            field=models.CharField(default=None, max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.CharField(default=None, max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Rut',
            field=models.CharField(default=None, max_length=50, verbose_name='Rut'),
        ),
    ]
