# Generated by Django 3.1.2 on 2021-02-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210210_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='BookingClientId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.client'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Rooms',
            field=models.IntegerField(default=None, verbose_name='Habitaciones'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='Address',
            field=models.CharField(default=None, max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='Descriptions',
            field=models.CharField(default=None, max_length=50, verbose_name='Descripcion Empresa'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre Hotel'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='Rut',
            field=models.CharField(default=None, max_length=50, verbose_name='Rut Empresa'),
        ),
    ]
