# Generated by Django 3.1.2 on 2021-02-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210215_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstype',
            name='RoomsId',
        ),
    ]
