# Generated by Django 3.1.2 on 2021-02-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_roomstype_roomsid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
