# Generated by Django 3.1.2 on 2021-02-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='RoomsName',
        ),
        migrations.AddField(
            model_name='booking',
            name='AubscriberMount',
            field=models.IntegerField(default=None, verbose_name='Monto PendienteS'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Prepaid',
            field=models.BooleanField(default=None, verbose_name='Prepagado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='BookingClientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.client'),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='FeaturesId',
        ),
        migrations.AddField(
            model_name='rooms',
            name='FeaturesId',
            field=models.ManyToManyField(to='booking.Features'),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='RoomsTypeId',
        ),
        migrations.AddField(
            model_name='rooms',
            name='RoomsTypeId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.roomstype'),
        ),
    ]
