# Generated by Django 3.1.2 on 2021-02-16 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210216_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='HotelsId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.hotels'),
        ),
    ]
