# Generated by Django 3.1.2 on 2021-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_hotelsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='RoomsId',
        ),
        migrations.AddField(
            model_name='features',
            name='RoomsId',
            field=models.ManyToManyField(to='booking.Rooms'),
        ),
    ]
