# Generated by Django 3.1.2 on 2021-02-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20210216_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='FeaturesId',
        ),
    ]
