# Generated by Django 3.1.2 on 2021-02-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_rooms_featuresid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='RoomsName',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
