# Generated by Django 3.1.2 on 2021-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_rooms_roomsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='Quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='rooms',
            name='RoomsCapacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='rooms',
            name='RoomsIs_active',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='rooms',
            name='RoomsPrice',
            field=models.IntegerField(default=None),
        ),
    ]
