# Generated by Django 3.1.2 on 2021-02-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210216_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='IdHotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.hotels'),
        ),
    ]
