# Generated by Django 3.1.2 on 2021-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210216_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='FeaturesId',
            field=models.ManyToManyField(to='booking.Features'),
        ),
    ]
