# Generated by Django 3.1.2 on 2021-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20210216_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='RoomsId',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='FeaturesId',
        ),
        migrations.AddField(
            model_name='rooms',
            name='FeaturesId',
            field=models.ManyToManyField(to='booking.Features'),
        ),
    ]
