# Generated by Django 3.1.2 on 2021-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_article_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
