# Generated by Django 3.1.2 on 2021-03-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20210216_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='AubscriberMount',
            field=models.IntegerField(default=None, verbose_name='Monto Pendiente'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='HotelsId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.hotels', verbose_name='Hotel'),
        ),
    ]
