# Generated by Django 3.1.2 on 2021-03-18 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20210317_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='TimeCheckIn',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='TimeCheckOut',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateCheckIn',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 23, 39, 25, 27153), verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateCheckOut',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 23, 39, 25, 27185), verbose_name='CheckOut'),
        ),
    ]
