# Generated by Django 3.1.2 on 2021-03-23 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20210317_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='DateCheckIn',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 16, 23, 24, 17236), verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateCheckOut',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 16, 23, 24, 17265), verbose_name='CheckOut'),
        ),
    ]
