# Generated by Django 3.1.2 on 2021-03-23 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20210323_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='DateCheckIn',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 16, 45, 54, 165036), verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateCheckOut',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 16, 45, 54, 165067), verbose_name='CheckOut'),
        ),
    ]
