# Generated by Django 3.1.2 on 2021-03-23 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20210323_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='DateCheckIn',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 19, 30, 4, 698135), verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateCheckOut',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 19, 30, 4, 698165), verbose_name='CheckOut'),
        ),
    ]
